twig:
    date:
        format: d.m.Y
        interval_format: '%%d days'
    globals:
        mode: '@App\Service\ModeService'
    form_themes:
        - 'bootstrap_5_layout.html.twig'

    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
