version: "3.9"

networks:
  traefik:
    external: true
  internal:
    external: false

volumes:
  php_socket:
  caddy_data:
  caddy_config:

services:
  php:
    image: ghcr.io/eventpoints/townpoint.io-php:main
    volumes:
      - php_socket:/var/run/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - database
    restart: unless-stopped
    environment:
      MERCURE_PUBLIC_URL: "https://townpoint.io/.well-known/mercure"
      APP_ENV: "prod"
      DATABASE_URL: "postgresql://__TOWNPOINT_POSTGRES_USER__:__TOWNPOINT_POSTGRES_PASSWORD__@database:5432/__TOWNPOINT_POSTGRES_DBNAME__?serverVersion=13&charset=utf8"
      MERCURE_JWT_SECRET: "__TOWNPOINT_MERCURE_JWT_SECRET__"
      MERCURE_JWT_SECRET: "__TOWNPOINT_MERCURE_JWT_SECRET__"
      APP_SECRET: "__TOWNPOINT_APP_SECRET__"
      MAILER_DSN: "__TOWNPOINT_MAILER_DSN__"
      MESSENGER_TRANSPORT_DSN: "__TOWNPOINT_MESSENGER_TRANSPORT_DSN__"
      APP_TIMEZONE: "__TOWNPOINT_APP_TIMEZONE__"
      CORS_ALLOW_ORIGIN: "__TOWNPOINT_CORS_ALLOW_ORIGIN__"
      CLOUDFLARE_TURNSTILE_PUBLIC_KEY: "__TOWNPOINT_CLOUDFLARE_TURNSTILE_PUBLIC_KEY__"
      CLOUDFLARE_TURNSTILE_PRIVATE_KEY: "__TOWNPOINT_CLOUDFLARE_TURNSTILE_PRIVATE_KEY__"
    networks:
      - internal

  caddy:
    image: ghcr.io/eventpoints/townpoint.io-caddy:main
    depends_on:
      - php
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "__TOWNPOINT_MERCURE_JWT_SECRET__"
      MERCURE_SUBSCRIBER_JWT_KEY: "__TOWNPOINT_MERCURE_JWT_SECRET__"
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.townpoint.rule=Host(`townpoint.io`, `www.townpoint.io`)"
      - "traefik.http.routers.townpoint.tls=true"
      - "traefik.http.routers.townpoint.tls.certresolver=le"
    networks:
      - traefik
      - internal

  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: "__TOWNPOINT_POSTGRES_DBNAME__"
      POSTGRES_PASSWORD: "__TOWNPOINT_POSTGRES_PASSWORD__"
      POSTGRES_USER: "__TOWNPOINT_POSTGRES_USER__"
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    networks:
      - internal

  asset-compile:
    image: ghcr.io/eventpoints/townpoint.io-php:main
    command: sh -c "bin/console tailwind:build --minify && bin/console asset-map:compile"
    depends_on:
      - php
    networks:
      - internal

  adminer:
    image: adminer:4.8.0
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: database
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.townpoint-adminer.rule=Host(`adminer.townpoint.io`)"
      - "traefik.http.routers.townpoint-adminer.tls=true"
      - "traefik.http.routers.townpoint-adminer.tls.certresolver=le"
    networks:
      - internal
      - traefik